# Generated by Django 3.2.3 on 2021-11-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.color')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('size', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.size')),
            ],
        ),
    ]
